/**
 * Advertising formulas. All return null when the denominator is zero/undefined.
 *
 *   CTR  = clicks / impressions
 *   CPC  = spend / clicks
 *   CVR  = orders / clicks
 *   CPA  = spend / orders
 *   ROAS = attributed revenue / spend
 *   Break-even ROAS = 1 / (margin before ads)
 *     where margin before ads = (net revenue − all variable costs except ads) / net revenue.
 *     A campaign below break-even ROAS loses money even if ROAS "looks" high.
 */
import { safeDivide } from './metric';

export const ctr = (clicks: number, impressions: number) => safeDivide(clicks, impressions);
export const cpc = (spend: number, clicks: number) => safeDivide(spend, clicks);
export const adCvr = (orders: number, clicks: number) => safeDivide(orders, clicks);
export const cpa = (spend: number, orders: number) => safeDivide(spend, orders);
export const roas = (attributedRevenue: number, spend: number) => safeDivide(attributedRevenue, spend);

/** Null when there is no positive margin before ads (no ROAS can break even). */
export function breakEvenRoas(marginBeforeAds: number | null): number | null {
  if (marginBeforeAds === null || !(marginBeforeAds > 0)) return null;
  return 1 / marginBeforeAds;
}

/**
 * Profit generated by an ad after its own cost:
 *   attributed revenue × margin before ads − spend.
 */
export function profitAfterAds(attributedRevenue: number, spend: number, marginBeforeAds: number | null): number | null {
  if (marginBeforeAds === null) return null;
  return attributedRevenue * marginBeforeAds - spend;
}
